### PR TITLE
Release 0.4.0

### PR DESCRIPTION
**Pull request by nsheff**
ready?

interested in: https://github.com/pepkit/attmap/issues/58
also: https://github.com/pepkit/peppy/issues/311

### CODE REVIEW

**Comment by nsheff** [comment]
@vreuter Are you satisfied with this? If so I'd say release it and then start the cascade...

**Comment by vreuter** [comment]
Do any dependents _need_ changed, or is it just a benefit? I.e., are there any packages that need a docs fix, or this will just make them better?

**Comment by nsheff** [comment]
they should just automatically look better next time they are built. nothing more to do here, thanks!

**Comment by vreuter** [comment]
:man_facepalming: https://github.com/pepkit/attmap/pull/60#issuecomment-499712346

**Comment by vreuter** [comment]
I didn't read the other notification first

**Comment by nsheff** [comment]
no worries, it's as easy as clicking 'build' in rtd :).

BTW, wow... this is *so* much better...

**Comment by nsheff** [comment]
Nice! http://attmap.databio.org/en/latest/autodoc_build/attmap/

**Pull request merged**
